version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - checkout
      - run:
          name: Update submodule
          command: git submodule update --init --recursive
      - restore_cache:
          keys: [cache-build]
      - run:
          name: build app
          command: |
            yarn
            yarn build
      - run:
          name: Copy dist folder
          command: cp -R platform/viewer/dist app

      - aws-s3/sync:
          from: platform/viewer/dist
          to: 's3://ohif-viewer-chestify'
      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: cache-build
      - persist_to_workspace:
          root: .
          paths:
            - app
            - build.zip

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run:
          name: Update submodule
          command: git submodule update --init --recursive
      - attach_workspace:
          at: .
      - eb/setup
      - run:
          name: deploy staging to EB
          command: |
            eb init viewer-5 -r us-east-1 -p Docker -k dashboard
            eb create viewer-5 -it t3.large
            eb deploy viewer-5
            eb status



workflows:
  default:
    jobs:
      - build
      - deploy:
          requires:
            - build
