version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - checkout
      - run:
          name: Update submodule
          command: git submodule update --init --recursive
      - restore_cache:
          keys: [cache-build]
      - run:
          name: build app
          command: |
            yarn
            yarn build
      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: cache-build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run:
          name: Update submodule
          command: git submodule update --init --recursive
      - attach_workspace:
          at: ~/
      - eb/setup
      - run:
          name: deploy staging to EB
          command: |
            eb init chestify-viewer-2 -r us-east-1 -p Docker -k dashboard
            eb create chestify-viewer-2 -it a1.4xlarge
            # cat .env | while IFS= read -r line; do key=$(echo $line | cut -d'=' -f1); value=$(echo $line | cut -d'=' -f2-); export $key="$value"; done
            eb deploy chestify-viewer-2
            eb status





workflows:
  default:
    jobs:
      - build
      - deploy:
          requires: [build]
          # filters:
          #   branches:
          #     only: [develop]
